// <auto-generated />
using System;
using GameVault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameVault.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327015939_AddPlatformVersionLinks")]
    partial class AddPlatformVersionLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameVault.Data.Models.GVPlatform", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext");

                    b.Property<string>("AlternativeName")
                        .HasColumnType("longtext");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Generation")
                        .HasColumnType("int");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsTracked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("PlatformFamilyIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlatformLogoIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlatformTypeIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("VersionsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("WebsitesIdsJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("PlatformFamilyIGDBId");

                    b.HasIndex("PlatformLogoIGDBId");

                    b.HasIndex("PlatformTypeIGDBId");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformFamily", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("PlatformFamilies");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformLogo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AlphaChannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Animated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("PlatformLogos");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformPlatformVersion", b =>
                {
                    b.Property<long>("PlatformIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlatformVersionIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("PlatformIGDBId", "PlatformVersionIGDBId");

                    b.HasIndex("PlatformVersionIGDBId");

                    b.ToTable("PlatformPlatformVersions");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("PlatformTypes");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CPU")
                        .HasColumnType("longtext");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<string>("CompaniesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Connectivity")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Graphics")
                        .HasColumnType("longtext");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MainManufacturerIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Media")
                        .HasColumnType("longtext");

                    b.Property<string>("Memory")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OS")
                        .HasColumnType("longtext");

                    b.Property<string>("Output")
                        .HasColumnType("longtext");

                    b.Property<long?>("PlatformLogoIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlatformVersionReleaseDatesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Resolutions")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Sound")
                        .HasColumnType("longtext");

                    b.Property<string>("Storage")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("MainManufacturerIGDBId");

                    b.HasIndex("PlatformLogoIGDBId");

                    b.ToTable("PlatformVersions");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatform", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVPlatformFamily", "PlatformFamily")
                        .WithMany()
                        .HasForeignKey("PlatformFamilyIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameVault.Data.Models.GVPlatformLogo", "PlatformLogo")
                        .WithMany()
                        .HasForeignKey("PlatformLogoIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameVault.Data.Models.GVPlatformType", "PlatformType")
                        .WithMany()
                        .HasForeignKey("PlatformTypeIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlatformFamily");

                    b.Navigation("PlatformLogo");

                    b.Navigation("PlatformType");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformPlatformVersion", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVPlatform", "Platform")
                        .WithMany("PlatformVersionLinks")
                        .HasForeignKey("PlatformIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVPlatformVersion", "PlatformVersion")
                        .WithMany("PlatformLinks")
                        .HasForeignKey("PlatformVersionIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("PlatformVersion");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersion", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVPlatformLogo", "PlatformLogo")
                        .WithMany()
                        .HasForeignKey("PlatformLogoIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlatformLogo");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatform", b =>
                {
                    b.Navigation("PlatformVersionLinks");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersion", b =>
                {
                    b.Navigation("PlatformLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
