// <auto-generated />
using System;
using GameVault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameVault.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416232038_AddLanguageSupportsForPerSystemSync")]
    partial class AddLanguageSupportsForPerSystemSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameVault.Data.Models.GVCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ChangedCompanyIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<int?>("Country")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DevelopedIdsJson")
                        .HasColumnType("longtext");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogoIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("ParentIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("WebsitesIdsJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgeRatingsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<double?>("AggregatedRating")
                        .HasColumnType("double");

                    b.Property<int?>("AggregatedRatingCount")
                        .HasColumnType("int");

                    b.Property<string>("AlternativeNamesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ArtworksIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("BundlesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<string>("CollectionsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<long?>("CoverIGDBId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalGamesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FirstReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ForksIdsJson")
                        .HasColumnType("longtext");

                    b.Property<long?>("FranchiseIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("FranchisesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("GameEnginesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("GameLocalizationsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("GameModesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<long?>("GameStatusIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GameTypeIGDBId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Hypes")
                        .HasColumnType("int");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("InvolvedCompaniesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocalOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPhysicallyOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTracked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("KeywordsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("LanguageSupportsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("MultiplayerModesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("ParentGameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlatformsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerPerspectivesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("PortsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("ReleaseDatesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RemakesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("RemastersIdsJson")
                        .HasColumnType("longtext");

                    b.Property<int?>("RetroAchievementsCompletedAchievements")
                        .HasColumnType("int");

                    b.Property<int?>("RetroAchievementsTotalAchievements")
                        .HasColumnType("int");

                    b.Property<string>("SimilarGamesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("StandaloneExpansionsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Storyline")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("TagsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ThemesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<double?>("TotalRating")
                        .HasColumnType("double");

                    b.Property<int?>("TotalRatingCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<long?>("VersionParentIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("VersionTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("WebsitesIdsJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CoverIGDBId");

                    b.HasIndex("FranchiseIGDBId");

                    b.HasIndex("GameStatusIGDBId");

                    b.HasIndex("GameTypeIGDBId");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("ParentGameIGDBId");

                    b.HasIndex("VersionParentIGDBId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameCover", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AlphaChannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Animated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageId")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("GameCovers");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameDlc", b =>
                {
                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("DlcIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("GameIGDBId", "DlcIGDBId");

                    b.HasIndex("DlcIGDBId");

                    b.ToTable("GameDlcs");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameExpandedGame", b =>
                {
                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpandedGameIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("GameIGDBId", "ExpandedGameIGDBId");

                    b.HasIndex("ExpandedGameIGDBId");

                    b.ToTable("GameExpandedGames");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameExpansion", b =>
                {
                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpansionIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("GameIGDBId", "ExpansionIGDBId");

                    b.HasIndex("ExpansionIGDBId");

                    b.ToTable("GameExpansions");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameGenre", b =>
                {
                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("GenreIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("GameIGDBId", "GenreIGDBId");

                    b.HasIndex("GenreIGDBId");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameRom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPhysicallyOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("PlatformIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RetroAchievementsGameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha1")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameIGDBId");

                    b.HasIndex("Md5");

                    b.HasIndex("RetroAchievementsGameId");

                    b.HasIndex("Sha1");

                    b.HasIndex("PlatformIGDBId", "FilePath")
                        .IsUnique();

                    b.ToTable("GameRoms");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameScreenshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AlphaChannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Animated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageId")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("GameScreenshots");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameScreenshotLink", b =>
                {
                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("ScreenshotIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("GameIGDBId", "ScreenshotIGDBId");

                    b.HasIndex("ScreenshotIGDBId");

                    b.ToTable("GameScreenshotLinks");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameVideo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VideoId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("GameVideos");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameVideoLink", b =>
                {
                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("VideoIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("GameIGDBId", "VideoIGDBId");

                    b.HasIndex("VideoIGDBId");

                    b.ToTable("GameVideoLinks");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGenre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVInvolvedCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<long?>("CompanyIGDBId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Developer")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Porting")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Publisher")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Supporting")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameIGDBId");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("InvolvedCompanies");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVLanguageSupport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("GameIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LanguageSupportTypeIGDBId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameIGDBId");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("LanguageIGDBId");

                    b.ToTable("LanguageSupports");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatform", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("longtext");

                    b.Property<string>("AlternativeName")
                        .HasColumnType("longtext");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Generation")
                        .HasColumnType("int");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsTracked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("PlatformFamilyIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlatformLogoIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlatformTypeIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RetroAchievementConsoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RomFolder")
                        .HasColumnType("longtext");

                    b.Property<string>("RomTypes")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<string>("VersionsIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("WebsitesIdsJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("PlatformFamilyIGDBId");

                    b.HasIndex("PlatformLogoIGDBId");

                    b.HasIndex("PlatformTypeIGDBId");

                    b.HasIndex("RetroAchievementConsoleId");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformFamily", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("PlatformFamilies");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformLogo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("AlphaChannel")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Animated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("PlatformLogos");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformPlatformVersion", b =>
                {
                    b.Property<long>("PlatformIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlatformVersionIGDBId")
                        .HasColumnType("bigint");

                    b.HasKey("PlatformIGDBId", "PlatformVersionIGDBId");

                    b.HasIndex("PlatformVersionIGDBId");

                    b.ToTable("PlatformPlatformVersions");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.ToTable("PlatformTypes");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CPU")
                        .HasColumnType("longtext");

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<string>("CompaniesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Connectivity")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Graphics")
                        .HasColumnType("longtext");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MainManufacturerIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Media")
                        .HasColumnType("longtext");

                    b.Property<string>("Memory")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OS")
                        .HasColumnType("longtext");

                    b.Property<string>("Output")
                        .HasColumnType("longtext");

                    b.Property<long?>("PlatformLogoIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlatformVersionReleaseDatesIdsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Resolutions")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Sound")
                        .HasColumnType("longtext");

                    b.Property<string>("Storage")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("MainManufacturerIGDBId");

                    b.HasIndex("PlatformLogoIGDBId");

                    b.ToTable("PlatformVersions");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersionReleaseDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DateFormatIGDBId")
                        .HasColumnType("bigint");

                    b.Property<string>("Human")
                        .HasColumnType("longtext");

                    b.Property<long>("IGDBId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("PlatformVersionIGDBId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReleaseRegionIGDBId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IGDBId")
                        .IsUnique();

                    b.HasIndex("PlatformVersionIGDBId");

                    b.ToTable("PlatformVersionReleaseDates");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVRetroAchievementConsole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("RetroAchievementsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RetroAchievementsId")
                        .IsUnique();

                    b.ToTable("RetroAchievementConsoles");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVRetroAchievementGame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AchievementsCount")
                        .HasColumnType("int");

                    b.Property<string>("ConsoleName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ForumTopicId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageIcon")
                        .HasColumnType("longtext");

                    b.Property<int>("LeaderboardsCount")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<long>("RetroAchievementConsoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("RetroAchievementsGameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RetroAchievementConsoleId");

                    b.HasIndex("RetroAchievementsGameId")
                        .IsUnique();

                    b.ToTable("RetroAchievementGames");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVRetroAchievementGameHash", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("RetroAchievementGameId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.HasIndex("RetroAchievementGameId", "Hash")
                        .IsUnique();

                    b.ToTable("RetroAchievementGameHashes");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGame", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGameCover", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameVault.Data.Models.GVGameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cover");

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameDlc", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Dlc")
                        .WithMany()
                        .HasForeignKey("DlcIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("DlcLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dlc");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameExpandedGame", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "ExpandedGame")
                        .WithMany()
                        .HasForeignKey("ExpandedGameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("ExpandedGameLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpandedGame");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameExpansion", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Expansion")
                        .WithMany()
                        .HasForeignKey("ExpansionIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("ExpansionLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expansion");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameGenre", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("GenreLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVGenre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameRom", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("RomFiles")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVPlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameScreenshotLink", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("ScreenshotLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVGameScreenshot", "Screenshot")
                        .WithMany()
                        .HasForeignKey("ScreenshotIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Screenshot");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGameVideoLink", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("VideoLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVGameVideo", "Video")
                        .WithMany()
                        .HasForeignKey("VideoIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVInvolvedCompany", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("InvolvedCompanyLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVLanguageSupport", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVGame", "Game")
                        .WithMany("LanguageSupportLinks")
                        .HasForeignKey("GameIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVLanguage", "Language")
                        .WithMany("GameLanguageSupports")
                        .HasForeignKey("LanguageIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatform", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVPlatformFamily", "PlatformFamily")
                        .WithMany()
                        .HasForeignKey("PlatformFamilyIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameVault.Data.Models.GVPlatformLogo", "PlatformLogo")
                        .WithMany()
                        .HasForeignKey("PlatformLogoIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameVault.Data.Models.GVPlatformType", "PlatformType")
                        .WithMany()
                        .HasForeignKey("PlatformTypeIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GameVault.Data.Models.GVRetroAchievementConsole", "RetroAchievementConsole")
                        .WithMany()
                        .HasForeignKey("RetroAchievementConsoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlatformFamily");

                    b.Navigation("PlatformLogo");

                    b.Navigation("PlatformType");

                    b.Navigation("RetroAchievementConsole");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformPlatformVersion", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVPlatform", "Platform")
                        .WithMany("PlatformVersionLinks")
                        .HasForeignKey("PlatformIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameVault.Data.Models.GVPlatformVersion", "PlatformVersion")
                        .WithMany("PlatformLinks")
                        .HasForeignKey("PlatformVersionIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("PlatformVersion");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersion", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVPlatformLogo", "PlatformLogo")
                        .WithMany()
                        .HasForeignKey("PlatformLogoIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlatformLogo");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersionReleaseDate", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVPlatformVersion", "PlatformVersion")
                        .WithMany("ReleaseDates")
                        .HasForeignKey("PlatformVersionIGDBId")
                        .HasPrincipalKey("IGDBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlatformVersion");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVRetroAchievementGame", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVRetroAchievementConsole", "RetroAchievementConsole")
                        .WithMany("Games")
                        .HasForeignKey("RetroAchievementConsoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetroAchievementConsole");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVRetroAchievementGameHash", b =>
                {
                    b.HasOne("GameVault.Data.Models.GVRetroAchievementGame", "RetroAchievementGame")
                        .WithMany("Hashes")
                        .HasForeignKey("RetroAchievementGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetroAchievementGame");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVGame", b =>
                {
                    b.Navigation("DlcLinks");

                    b.Navigation("ExpandedGameLinks");

                    b.Navigation("ExpansionLinks");

                    b.Navigation("GenreLinks");

                    b.Navigation("InvolvedCompanyLinks");

                    b.Navigation("LanguageSupportLinks");

                    b.Navigation("RomFiles");

                    b.Navigation("ScreenshotLinks");

                    b.Navigation("VideoLinks");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVLanguage", b =>
                {
                    b.Navigation("GameLanguageSupports");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatform", b =>
                {
                    b.Navigation("PlatformVersionLinks");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVPlatformVersion", b =>
                {
                    b.Navigation("PlatformLinks");

                    b.Navigation("ReleaseDates");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVRetroAchievementConsole", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameVault.Data.Models.GVRetroAchievementGame", b =>
                {
                    b.Navigation("Hashes");
                });
#pragma warning restore 612, 618
        }
    }
}
