name: Delete tags from DockerHub

on:
  pull_request:
    types: [closed]

jobs:
  delete-tag:
    runs-on: unraid
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    if: ${{ github.event.pull_request.head.ref != 'main' }}

    steps:
      - name: Delete Docker Hub Tag
        uses: xhofe/del-docker-tag@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gamevault:${{ github.event.pull_request.head.ref }}